
---
- name: Security hardening for Amazon Linux
  hosts: amazon_linux
  become: yes

  tasks:
    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify:
        - restart sshd

    - name: Enable automatic security updates
      package:
        name: yum-cron
        state: present

    - name: Start and enable yum-cron service
      service:
        name: yum-cron
        state: started
        enabled: yes

    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow SSH, HTTP, and HTTPS services
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - ssh
        - http
        - https
      notify:
        - reload firewalld

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: reload firewalld
      service:
        name: firewalld
        state: reloaded
